### ISSUE TITLE
Decryption error

### ISSUE THREAD

**Issue by uksus70** [axuan25/kaa-docker#2]
Have you faced such an error on endpoint connection?
```
kaa_1 | 2016-04-11 09:55:23,089 [nioEventLoopGroup-3-4] INFO  o.k.k.s.t.h.t.n.DefaultHttpServerInitializer - DefaultServerInitializer Initializing Channel 494acf6d-c627-4e12-8e89-fa9770d1d59d connection from /46.173.5.37:61420
kaa_1 | 2016-04-11 09:55:23,124 [nioEventLoopGroup-3-4] ERROR o.k.k.s.t.h.t.n.DefaultExceptionHandler - Exception caught
kaa_1 | javax.crypto.BadPaddingException: Decryption error
kaa_1 |         at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:380) ~[na:1.8.0_77]
kaa_1 |         at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:291) ~[na:1.8.0_77]
kaa_1 |         at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363) ~[sunjce_provider.jar:1.8.0_71]
kaa_1 |         at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) ~[sunjce_provider.jar:1.8.0_71]
kaa_1 |         at javax.crypto.Cipher.doFinal(Cipher.java:2165) ~[na:1.8.0_71]
kaa_1 |         at org.kaaproject.kaa.common.endpoint.security.MessageEncoderDecoder.decodeSessionKey(MessageEncoderDecoder.java:217) ~[endpoint-shared-0.8.1.jar:na]
kaa_1 |         at org.kaaproject.kaa.common.endpoint.security.MessageEncoderDecoder.decodeData(MessageEncoderDecoder.java:209) ~[endpoint-shared-0.8.1.jar:na]
kaa_1 |         at org.kaaproject.kaa.server.bootstrap.service.transport.BootstrapTransportService$BootstrapMessageHandler$1.decodeEncryptedRequest(BootstrapTransportService.java:237) ~[kaa-node-0.8.1.jar:na]
kaa_1 |         at org.kaaproject.kaa.server.bootstrap.service.transport.BootstrapTransportService$BootstrapMessageHandler$1.decodeRequest(BootstrapTransportService.java:222) ~[kaa-node-0.8.1.jar:na]
kaa_1 |         at org.kaaproject.kaa.server.bootstrap.service.transport.BootstrapTransportService$BootstrapMessageHandler$1.run(BootstrapTransportService.java:163) ~[kaa-node-0.8.1.jar:na]
kaa_1 |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_77]
kaa_1 |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_77]
kaa_1 |         at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
kaa_1 | 2016-04-11 09:55:23,124 [nioEventLoopGroup-3-4] WARN  o.k.k.s.t.h.t.netty.ResponseEncoder - Session [494acf6d-c627-4e12-8e89-fa9770d1d59d] got invalid HTTP response: DefaultFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: UnpooledUnsafeHeapByteBuf(ridx: 0, widx: 16, cap: 48))
kaa_1 | HTTP/1.1 500 Internal Server Error
kaa_1 | Content-Type: text/plain; charset=UTF-8
kaa_1 | Content-Length: 16
kaa_1 | Connection: close
```

**Comment by axuan25** [comment]
Dear Anthony,

I have not encountered this error. Has this been occurring to you while
only using the docker image?
I will have time to look into it in a day or two, only, unfortunately.

Best regards,
Christopher

Christopher Burroughs 歐陽軒
B.A. Asian Studies, Option I: China & Taiwan
University of California, Berkeley | 2014
+1-714-752-3340 | axuan@chrisplusplus.net

On Mon, Apr 11, 2016 at 2:01 PM, Anthony Serdyukov <notifications@github.com

**Comment by uksus70** [comment]
Yes, only in the docker. Afterwards I have deployed KAA on the host machine and it worked fine.
Here is my `docker-compose.yml`:
```
version: '2'
services:
  kaa_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=kaa
  kaa:
    build: kaa/0.8/
    depends_on:
      - kaa_db
      - mongo
      - zookeeper
    links:
      - "kaa_db:db"
    environment:
      - ZOOKEEPER_IP=zookeeper
      - JDBC_HOST=db
      - MONGODB_NODE_LIST=mongo:27017
      - NOSQL_DB_PROVIDER_NAME=mongodb
      - TRANSPORT_PUBLIC_INTERFACE
    ports:
      - "8080:8080"
      - "9888:9888"
      - "9889:9889"
      - "9997:9997"
      - "9999:9999"
  zookeeper:
    image: jplock/zookeeper
  mongo:
    image: mongo
```

**Comment by axuan25** [comment]
Hello Anthony,

I do not use docker-compose to launch our Kaa node at my company, although
I see no reason for it to not work; I do worry about containers not being
fully initiated before the Kaa-node service runs for the first time (though
it doesn't seem to be the issue here).

Is there any reason why TRANSPORT_PUBLIC_INTERFACE is left blank?

Further, we do stick to Kaa's specified versions for Mongo, Zookeeper and
postgres (2.6.9, 3.4.5, 9.4 respectively), although i've been using
jplock's 3.4.8 tag without issues. By not specifying any image tag and thus
using their latest versions, I cannot guarantee anything.

I will have a chance to look into this in more detail later this week. I
hope your problem does not persist, please let me know if you were able to
fix it or not. Otherwise, I will get back to you and try to reproduce your
problem.

Best,
Christopher

Christopher Burroughs 歐陽軒
B.A. Asian Studies, Option I: China & Taiwan
University of California, Berkeley | 2014
+1-714-752-3340 | axuan@chrisplusplus.net

On Tue, Apr 12, 2016 at 5:04 AM, Anthony Serdyukov <notifications@github.com

**Comment by axuan25** [comment]
Hello, Anthony,

I've finally run into this bug myself. I am currently looking into it, but so far it seems to be a bug on Kaa's end. Have you, by any chance, resolved this issue already?

Best,
Christopher

**Comment by uksus70** [comment]
Thank you Christopher for your endeavour.

Actually I have not resolved it yet and I also think it is some bug on the KAA side.

Afterwards I have noticed that I was using latest versions of Postgres and Cassandra docker images and it deffiers from [recommended versions](http://docs.kaaproject.org/display/KAA/Installation+guide#Installationguide-Thirdpartycomponents.1), but I don't this is the cause of this problem.

In regard to `TRANSPORT_PUBLIC_INTERFACE`, it is left blank according to `docker-compose` syntax that means to get the variable from the host environment.

Taking into account that in 0.9.0 they promise to release official docker image (http://jira.kaaproject.org/browse/KAA-416), we should just wait.

**Comment by axuan25** [comment]
Hello Anthony,

It seems I encountered the error after turning the Kaa docker container on/off a few times; I am still unable to explain the exact cause of the error, but my guess is that it is related to a difference in network, rendering the public & private keys incompatible. I was able to resolve the issue by re-generating an SDK for my client, and the decryption error disappeared.

I will be contributing to Kaa's official docker image, therefore I would like to get to the bottom of this. I will be trying to reproduce the bug to find its exact origin, and then notify the Kaa dev team.

Best,
Christopher
